name: CI build Windows
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  xdp-root-build-windows:
    strategy:
      matrix:
        configurations: ['Debug', 'Release']
    runs-on: windows-2019
    env:
      BUILD_CONFIGURATION: ${{matrix.configurations}}
      BUILD_PLATFORM: x64

    steps:
      - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415
        with:
          submodules: "recursive"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@becb80cf9a036187bb1e07e74eb64e25850d757a

      - name: Install tools
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          choco install -y llvm
          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cmake -B build
          cmake --build build -j $(nproc) --config ${{env.BUILD_CONFIGURATION}}
 
      - name: Create artifact directory
        run: |
          mkdir upload_artifact_xdp_root upload_artifact_ratelimiting
          copy D:\a\eBPF-Package-Repository\eBPF-Package-Repository\xdp-root\build\xdp_root_kern.o upload_artifact_xdp_root
          copy D:\a\eBPF-Package-Repository\eBPF-Package-Repository\build\xdp-root\${{env.BUILD_CONFIGURATION}}\xdp_root.exe upload_artifact_xdp_root
          copy D:\a\eBPF-Package-Repository\eBPF-Package-Repository\ratelimiting\build\ratelimiting_kern.o upload_artifact_ratelimiting

      - name: Upload xdp-root
        uses: actions/upload-artifact@v3
        with:
          name: xdp-root-windows-${{env.BUILD_CONFIGURATION}}-artifact
          path: upload_artifact_xdp_root

      - name: Upload ratelimiting
        uses: actions/upload-artifact@v3
        with:
          name: ratelimiting-windows-${{env.BUILD_CONFIGURATION}}-artifact
          path: upload_artifact_ratelimiting

